# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportingmgr', to='randr.Associate'),
        ),
    ]
