# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randr', '0002_auto_20161023_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='recognition_by',
            field=models.CharField(blank=True, default='Unknown', max_length=10),
            preserve_default=False,
        ),
    ]
