# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randr', '0003_auto_20161118_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='recognition_by',
            field=models.ForeignKey(blank=True, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='recog_associate', to='randr.Associate'),
        ),
    ]
