# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randr', '0004_auto_20161118_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='id',
        ),
        migrations.AddField(
            model_name='associate',
            name='employee_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='associate',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
